name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "8.12.0"
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10"
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install
      - name: Setup protoc-gen-openapiv2
        run: |
          curl -sSL https://github.com/grpc-ecosystem/grpc-gateway/releases/download/v2.23.0/protoc-gen-openapiv2-v2.23.0-linux-x86_64 -o protoc-gen-openapiv2
          chmod +x protoc-gen-openapiv2
          mv protoc-gen-openapiv2 /usr/local/bin
      - name: Build
        run: pnpm build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs
          name: github-pages

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
