name: Update proto
on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repository: [meline]
    steps:
      - name: Generate token for proto
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ vars.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PEM }}
      - name: Repository dispatch for proto
        run: |
          curl -fL \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}"\
            https://api.github.com/repos/saitamau-maximum/${{ matrix.repository }}/dispatches \
            -d '{"event_type":"proto"}'

